### ISSUE TITLE
Google Scholar crawling 

### ISSUE THREAD

**Issue by genomematt** [openjournals/joss#130] opened 2016-06-03 12:39 UTC
It does not at the moment look like JOSS is being indexed by google scholar.
I think this is one of the sites we want to ensure visibility for the journal on.

https://scholar.google.com.au/intl/en/scholar/inclusion.html#troubleshooting

**Comment by arfon** [comment] 2016-06-03 13:31
JOSS papers have included the Google Scholar metadata tags since [this update](https://github.com/openjournals/whedon/commit/4784cff8aec87cc3e10d454294bf06a02f8f6a10) about 10 days ago.

Their docs suggest it can take 4-6 weeks to be indexed so I think we're still in that window. Let's leave this open for now to keep tracking this issue. I agree we must be indexed by Google Scholar, I'm just not sure there's anything we need to do other than wait at this point 🕐

**Comment by pjotrp** [comment] 2016-07-15 05:39
Excellent!

**Comment by sherrillmix** [comment] 2016-09-22 12:40
At least a couple papers show up now:
https://scholar.google.com/scholar?hl=en&q=GeneNetwork%3A+framework+for+web-based+genetics
https://scholar.google.com/scholar?hl=en&q=R3D2%3A+Relativistic+Reactive+Riemann+problem+solver+for+Deflagrations+and+Detonations

However other articles on the same page currently do not:
https://scholar.google.com/scholar?q=Xenomapper%3A+Mapping+reads+in+a+mixed+species+context
https://scholar.google.com/scholar?q=pyuca%3A+a+Python+implementation+of+the+Unicode+Collation+Algorithm

Pretty cool that some are showing anyway and maybe google's getting around to processing the others.

**Comment by arfon** [comment] 2016-09-23 19:24
@sherrillmix, thanks for finding these. Let's keep monitoring this.

**Comment by FaustinCarter** [comment] 2016-12-18 21:34
It looks like Google Scholar is not actually indexing anything from JOSS. The two examples listed by @sherrillmix only show up in Google Scholar because the first is also listed at researchgate.net and the second is listed at eprints.soton.ac.uk. Google Scholar is indexing them based off those domains, not because of anything going on at JOSS.

**Comment by cMadan** [comment] 2016-12-19 01:53
Maybe Google Scholar isn't crawling through the Github links? My JOSS paper is indexed, but that's from being uploaded to my own website (https://scholar.google.com/citations?view_op=view_citation&citation_for_view=2QJwoAwAAAAJ:3BvdIg-l-ZAC), but I feel like that's still sufficiently different than being on researchgate or a university's own repository.

**Comment by pjotrp** [comment] 2016-12-25 04:03
Maybe it is an idea to move the static pages off github anyway. I know people who do not want to publish with JOSS because of the tight github connection. I think it will be fine to use the issue tracker etc., but at least it won't look like JOSS being a github subsidiary.

**Comment by cMadan** [comment] 2016-12-25 10:03
Github pages is more integrated now (no longer requires the gh-pages branch). It might be easier to switch to that now, rather than having the paper PDFs being loaded through the Github file preview.

**Comment by kyleniemeyer** [comment] 2017-03-08 05:04
OK, so I actually just submitted JOSS to Google Scholar page for requesting indexing of a journal. This is the (automated) response I got: 

> Homepage: http://joss.theoj.org
>Contact name: Kyle Niemeyer
>Contact email: kyle.niemeyer@gmail.com
>Inclusion type: Other journal website
>Inclusion size: 51-100
>Volume URLs: http://joss.theoj.org/papers/popular
>Issue URLs: http://joss.theoj.org/papers/popular
>TOC URLs: http://joss.theoj.org/papers/popular
>Abstract URLs: http://joss.theoj.org/papers/10.21105/joss.00194
> http://joss.theoj.org/papers/10.21105/joss.00011
> http://joss.theoj.org/papers/10.21105/joss.00189
>Article URLs: https://github.com/openjournals/joss-papers/blob/master/joss.00194/10.21105.joss.00194.pdf
>https://github.com/openjournals/joss-papers/blob/master/joss.00011/10.21105.joss.00011.pdf
>https://github.com/openjournals/joss-papers/blob/master/joss.00189/10.21105.joss.00189.pdf
>https://github.com/openjournals/joss-papers/blob/master/joss.00012/10.21105.joss.00012.pdf
>https://github.com/openjournals/joss-papers/blob/master/joss.00016/10.21105.joss.00016.pdf
>If your content meets our guidelines, you can generally expect to find it included within the Google Scholar results within 4-6 weeks.
>
>Please keep in mind that bibliographic data is extracted from your pages by automatic software. If you aren’t satisfied with the accuracy of your listings, please refer to our technical guidelines at http://scholar.google.com/intl/en/scholar/inclusion.html for ways to provide more accurate bibliographic data.
>
>Regards,
>
>The Google Scholar team

I agree that having the paper PDFs linked to directly rather than the GitHub file preview may be smart—not sure if that will matter for Google Scholar.

**Comment by arfon** [comment] 2017-03-10 15:13
> I agree that having the paper PDFs linked to directly rather than the GitHub file preview may be smart—not sure if that will matter for Google Scholar.

Just incase that's an issue I've updated the URLs on the site to link to the 'raw' GitHub URLs which means they don't display in the GitHub UI. An example of this is:

- Old: https://github.com/openjournals/joss-papers/blob/master/joss.00194/10.21105.joss.00194.pdf
- New: https://github.com/openjournals/joss-papers/raw/master/joss.00194/10.21105.joss.00194.pdf

**Comment by wojdyr** [comment] 2017-07-05 10:17
I used to have the same problem a couple years ago when I put reprints of my papers into a github repository. I waited more than a year and it was still not in Google Scholar. Then I moved PDFs to a repository served through github pages -- and this helped.

I cannot be sure what the issue was, but perhaps it's because PDFs from github.com/.../raw/master/... are served as Content-Type "application/octet-stream" instead of "application/pdf".

Additional benefit of serving PDFs through github pages would be that the URL would look better, e.g.
https://openjournals.github.io/joss-articles/10.21105.joss.00194.pdf

**Comment by arfon** [comment] 2017-07-06 05:58
> I used to have the same problem a couple years ago when I put reprints of my papers into a github repository. I waited more than a year and it was still not in Google Scholar. Then I moved PDFs to a repository served through github pages -- and this helped.

👍 thanks @wojdyr, that's very helpful. Good point about the `application/octet-stream` content type possibly upsetting the Google bot.

**Comment by arfon** [comment] 2017-09-22 00:01
> 👍 thanks @wojdyr, that's very helpful. Good point about the application/octet-stream content type possibly upsetting the Google bot.

OK in https://github.com/openjournals/whedon/pull/11 I've modified the URLs we're serving to e.g. http://www.theoj.org/joss-papers/joss.00411/10.21105.joss.00411.pdf

**Comment by FaustinCarter** [comment] 2017-10-06 22:16
My paper is now indexed on Google Scholar! Others should check as well. That last modification might have done the trick.

**Comment by arfon** [comment] 2017-10-07 00:36
Which paper is that @FaustinCarter?

**Comment by FaustinCarter** [comment] 2017-10-07 00:43
Actually, my excitement may have been premature. It looks like it may only be indexed because it was listed as a citation here (thanks to the kind soul who cited it in a more traditional publication): http://adsabs.harvard.edu//abs/2016JOSS.2016...46B.

The JOSS link is: http://joss.theoj.org/papers/10.21105/joss.00046

If you search for "pygtc" on http://scholar.google.com it shows up as the first link, but with a "[CITATION]" tag preceding the title. I think this means that it is grabbing it from the adsabs rather than indexing it directly. This is further motivated by the fact that on both Google Scholar and the Harvard Adsabs service the abstract is listed as "Not available".

**Comment by arfon** [comment] 2017-12-03 17:05
I believe this is now fixed.

**Comment by arfon** [comment] 2017-12-03 17:06
See https://scholar.google.com/scholar?hl=en&as_sdt=0%2C9&q=10.21105&btnG= for example.

**Closed by arfon** 2017-12-03 17:05 UTC

**Comment by Benjamin-Lee** [comment] 2018-11-10 06:46
Still a little confused as to why [my paper](https://joss.theoj.org/papers/8adf6bd9fd6391d5343d15ea0b6b6525) isn't being listed. @arfon is there any reason you can think of?

**Comment by arfon** [comment] 2018-11-10 11:54
@Benjamin-Lee - not sure. I'm following up with some folks about this.

**Comment by FaustinCarter** [comment] 2018-11-10 12:16
Another paper that hasn't made it is: https://joss.theoj.org/papers/cf6f8ac309d6a18b6d6cf08b64aa3f62

**Comment by arfon** [comment] 2018-11-10 12:18
@FaustinCarter - yes, it looks like something stopped working in early August this year.

**Comment by eendebakpt** [comment] 2019-01-06 22:51
@arfon This https://joss.theoj.org/papers/0c6638f84a1a574913ed7c6dd1051847 paper was indexed, but the date was not (yet) extracted. The format of the JOSS papers does not meet the specifications that google scholar used to have. The specifications  have changed a little but, currently, the date in joss papers is not as suggested at https://scholar.google.com/intl/en/scholar/inclusion.html#indexing section 2.a.C. 
This issue was closed some time ago, should we reopen a new issue?

**Comment by arfon** [comment] 2019-01-07 04:52
> This issue was closed some time ago, should we reopen a new issue?

AFAIK, Google Scholar doesn't index us directly, rather, our papers are picked up via [ADS](https://adsabs.harvard.edu/). I'll follow up with the folks at ADS to see if there's something different we should be doing.

**Comment by leios** [comment] 2019-01-18 03:40
I was going to create a new issue for this, but seeing as there seems to be recent discussion on this thread, I would like to also mention that our article does not seem to be picked up by Google Scholar. 

I don't know if this information is helpful, but the last article that seems to be picked up by theoj.org is this one (50 days ago): https://www.theoj.org/joss-papers/joss.01102/10.21105.joss.01102.pdf.

The last one picked up by ads is this one (147 days ago): http://adsabs.harvard.edu/abs/2018JOSS....3..854M

It seems indexing via google scholar seems to have stopped roughly 50 days ago, but there doesn't seem to be any PR that should affect this around that time. I suppose a solution for now would be to upload my article to an institutional repository of my university?

**Comment by kgjerde** [comment] 2019-07-02 11:02
@arfon 

I wonder if this might be the problem:

1. Published JOSS paper pages now seem to leave the Google Scholar tag "citation_author" empty:
`<meta name="citation_author" content="">`.
Example: https://joss.theoj.org/papers/10.21105/joss.01342

2. Google Scholar (https://scholar.google.com/intl/en/scholar/inclusion.html#indexing) states that:

> At least one author tag is required for inclusion in Google Scholar.

The time frame of the problem, as stated by you, supports this hypothesis:
> @FaustinCarter - yes, it looks like something stopped working in early August this year.

Paper from 1 September 2018 with no author tag: https://joss.theoj.org/papers/efb9242db91adee8c8265f000f26ef5a

Paper from 29 June 2018 with author tag:
https://joss.theoj.org/papers/049f6d3dab9391e8353484028148dd0d

**Comment by mschubert** [comment] 2019-07-27 11:09
The

```html
<meta name="citation_author" content="">
```

tag is not enough to explain the missing indexing. I checked some of the papers below, and it doesn't explain why some are listed from JOSS (denoted by <sup>empty</sup>)

However, there's definitely still issue with Google Scholar indexing. Maybe this issue should be reopened? @arfon 

From 1 month ago:

* [treex](https://joss.theoj.org/papers/0800c3bd9442b5e21b607776d7df666a) - *indexed*, but also multiple citations <sup>empty</sup>
* ![#c5f015](https://placehold.it/15/c5f015/000000?text=+) [diwanalr](https://joss.theoj.org/papers/a5f7da635b799f4befef712ec0a59127) - *actually indexed from theoj.org* <sup>empty</sup>
* ![#f03c15](https://placehold.it/15/f03c15/000000?text=+) [sbpy](https://joss.theoj.org/papers/8b8e7bb15fb4a14f80f2afd06b6ce060) - **not indexed** <sup>empty</sup>
* ![#c5f015](https://placehold.it/15/c5f015/000000?text=+) [phylosmith](https://joss.theoj.org/papers/4d4780ab16c487764ebe108fa6bcdc2c) - *actually indexed from theoj.org* <sup>empty</sup>
* [Multi-attribute task builder](https://joss.theoj.org/papers/30958288f2384aab953294c6b9cc9b73) - *actually indexed from theoj.org* <sup>empty</sup>

Also 2 months:

* ![#f03c15](https://placehold.it/15/f03c15/000000?text=+) [QMRTools](https://joss.theoj.org/papers/ef8bfb6c31499845d353b6a5af0d6300) - **not indexed** <sup>empty</sup>
* [stingray](https://joss.theoj.org/papers/90ccde24769778c954dc9830800e019e) - *indexed*, but also in arXiv <sup>empty</sup>
* [MPIFiles.jl](https://joss.theoj.org/papers/0e06aa80b90b3aaee0cf3a9da52f3760) - *indexed*, but also cited from the International Journal on Magnetic Particle Imaging <sup>empty</sup>
* ![#c5f015](https://placehold.it/15/c5f015/000000?text=+) [SMACT](https://joss.theoj.org/papers/7efd2f2ad60d25bdccee3fbd3fc11448) - *actually indexed from theoj.org* <sup>empty</sup>
* ![#f03c15](https://placehold.it/15/f03c15/000000?text=+) [pymcmcstat](https://joss.theoj.org/papers/5ac18236dc3f11e9f46977fc43f61991) - **only indexed as citation** <sup>empty</sup>

Also 3 months ago:

* [HRDS](https://joss.theoj.org/papers/d8f85d9247eef870a36ce3a9ccb6b64b) - *indexed*, but from eprints.whiterose.ac.uk <sup>empty</sup>
* [anesthetic](https://joss.theoj.org/papers/8c51bffda75d122cf4a8b991e18d3e45) - *indexed*, but from arXiv <sup>empty</sup>
* [AMReX](https://joss.theoj.org/papers/8549074fbc29175a9823c1aca2f26d24) - *indexed*, but from cloudfront.escholarship.org <sup>empty</sup>
* ![#c5f015](https://placehold.it/15/c5f015/000000?text=+) [ggparliament](https://joss.theoj.org/papers/e90b0874dfb70891d3c2b2a781993ba9) - *actually indexed from theoj.org* <sup>empty</sup>
* ![#f03c15](https://placehold.it/15/f03c15/000000?text=+) [rGUIDANCE](https://joss.theoj.org/papers/b8b70cb72a3ec8331353795e3f83cfca) - **only indexed as citation** <sup>empty</sup>
* ![#f03c15](https://placehold.it/15/f03c15/000000?text=+) [uJVM](https://joss.theoj.org/papers/23161710ad8996910f329efc48c2f1a1) - **only indexed as citation** <sup>empty</sup>

Also 6 months ago:

* [Multiblock PLS](https://joss.theoj.org/papers/864e8fb9bc214f14b878c6c559e3031c) - *indexed*, but also on orbit.dtu.dk <sup>empty</sup>
* [fibergen](https://joss.theoj.org/papers/add4f02dcedfaae8f81da200000d64ee) - *indexed*, but also on researchgate <sup>empty</sup>
* [BladeX](https://joss.theoj.org/papers/5b0ef70a351c1a51daf3a9354cd7b3fa) - *indexed*, but also on researchgate and arXiv <sup>empty</sup>

**Comment by arfon** [comment] 2019-08-04 01:11
Hi all, thanks for digging into this further. A couple of things:

- I've just pushed an update to the site which should mean the `<meta name="citation_author" content="">` tag is now populated for all paper.
- I'm working with the folks at [ADS](https://ui.adsabs.harvard.edu/) to have JOSS indexed more regularly (daily) which should mean that papers start showing up on Google Scholar more rapidly.

I'm not sure what more to do at this point but am open to suggestions/improvements.

**Comment by pgrete** [comment] 2019-11-22 16:52
Is there any update on this, e.g., is there a way to manually update the indexing? (Specifically asking for https://joss.theoj.org/papers/10.21105/joss.01636) As a side note I noticed that the "Copy bibtex button" doesn't seem to get updated automatically.

**Comment by labarba** [comment] 2019-11-22 16:57
I looked up that paper on Google Scholar, [using the title](https://scholar.google.com/scholar?hl=en&as_sdt=0%2C6&q=ENZO%3A+An+Adaptive+Mesh+Refinement+Code+for+Astrophysics+%28Version+2.6%29&btnG=), and in this case it is being indexed through `adsabs.harvard.edu`.

The citation info in Harvard style is given as: 

> Brummel-Smith, C., Bryan, G., Butsky, I., Corlies, L., Emerick, A., Forbes, J., Fujimoto, Y., Goldbaum, N., Grete, P., Hummels, C. and Kim, J.H., 2019. ENZO: An Adaptive Mesh Refinement Code for Astrophysics (Version 2.6). The Journal of Open Source Software, 4.

and the BibTeX is given as:

```
@article{brummel2019enzo,
  title={ENZO: An Adaptive Mesh Refinement Code for Astrophysics (Version 2.6)},
  author={Brummel-Smith, Corey and Bryan, Greg and Butsky, Iryna and Corlies, Lauren and Emerick, Andrew and Forbes, John and Fujimoto, Yusuke and Goldbaum, Nathan and Grete, Philipp and Hummels, Cameron and others},
  journal={The Journal of Open Source Software},
  volume={4},
  year={2019}
}
```

... which all seems OK. What is your concern about the indexing of this article?

**Comment by pgrete** [comment] 2019-11-22 17:23
I see. Looks like I got confused because the authors are not parsed from ADS.
Regarding bibtex, when I click the button the content that ends up in my clipboard is "BibTex entry not available. Please check back later."

**Comment by labarba** [comment] 2019-11-22 17:29
Oh, I was grabbing the BibTeX info from the Google Scholar "Cite" dialog, not the JOSS website.

**Comment by arfon** [comment] 2019-11-22 19:00
> Regarding bibtex, when I click the button the content that ends up in my clipboard is "BibTex entry not available. Please check back later."

Yeah, this is super-buggy and I've just removed it from the UI for now until we can find a long-term fix.

**Comment by sgbaird** [comment] 2022-08-05 00:38
Any recommendations/updates in 2022?

**Comment by arfon** [comment] 2022-08-05 15:08
> Any recommendations/updates in 2022?

On what in particular sorry?

**Comment by sgbaird** [comment] 2022-08-05 17:11
@arfon, sorry - for ensuring that a particular JOSS article gets indexed on Google Scholar for all co-authors.

**Comment by arfon** [comment] 2022-08-06 16:05
> @arfon, sorry - for ensuring that a particular JOSS article gets indexed on Google Scholar for all co-authors.

Are you having issues with one of your papers being indexed? If so, could you describe the issue in more detail please?

**Comment by sgbaird** [comment] 2022-08-06 16:09
@arfon [looks like it went through OK](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=UACmnBgAAAAJ&citation_for_view=UACmnBgAAAAJ:MXK_kJrjxJIC). Just required some more patience on my part. Thanks!

**Comment by arfon** [comment] 2022-08-06 16:11
Great stuff!

**Comment by mschubert** [comment] 2022-08-07 18:05
Now that this was brought up again, I still see issues with GS correctly identifying citations.

For instance, [this article](https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=%22The+targets+R+package%3A+a+dynamic+make-like+function-oriented+pipeline+toolkit+for+reproducibility+and+high-performance+computing%22&btnG=) cites [my work here](https://academic.oup.com/bioinformatics/article/35/21/4493/5499081), but the [citation is not listed in GS](https://scholar.google.com/scholar?oi=bibs&hl=en&cites=16447849395281285186) (but *is listed* in e.g. [Dimensions](https://app.dimensions.ai/details/publication/pub.1115222374)).

Have others experienced similar things, or could this be caused by the line break in the journal name? (I can open up a separate issue if that's helpful)

**Comment by arfon** [comment] 2022-08-15 07:27
Not sure sorry. Google Scholar is a bit of a black box to us all.

**Comment by arfon** [comment] 2023-11-15 15:55
I'm afraid not @ManavalanG . We don't have any visibility into the Google Scholar operations.

**Comment by hauschke** [comment] 2023-11-16 09:37
Articles are being added: https://scholar.google.com/scholar?hl=de&as_sdt=0%2C5&q=source%3Ajoss+OR+source%3A%22Journal+of+Open+Source+Software%22&btnG=

But it takes a long while.

**Comment by ManavalanG** [comment] 2023-11-16 14:43
@hauschke [My article](https://joss.theoj.org/papers/10.21105/joss.05313) was published on Oct 23 and is yet to be seen by google scholar. However when I checked multiple articles that were published in JOSS since then, all of them showed up in google scholar including an [article published on Nov 11](https://scholar.google.com/scholar?hl=de&as_sdt=0%2C5&q=ER-Evaluation%3A+End-to-End+Evaluation+of+Entity+Resolution+Systems&btnG=). This made me curious :)

**Comment by ManavalanG** [comment] 2024-02-07 17:27
Hi! I just wanted to note that [my article published on Oct 2023](https://joss.theoj.org/papers/10.21105/joss.05313) is yet to appear in google scholar 😞 I checked if there is a mechanism on my end to make it available via google scholar, but I didn't find any. I gather from the earlier conversation that JOSS admins can't do much about it, but I wanted to register my frustration here 😢

**Comment by ManavalanG** [comment] 2024-05-06 18:53
[My paper](https://scholar.google.com/scholar?hl=en&as_sdt=0%2C1&q=QuaC%3A+A+Pipeline+Implementing+Quality+Control+Best+Practices+for+Genome+Sequencing+and+Exome+Sequencing+Data&btnG=) has finally made it to google scholar a month or so ago, but it still doesn't appear in google scholar feed of mine or other authors. Looks like this is similar to the issue mentioned by @Spaak.

**Comment by matsvanes** [comment] 2024-05-06 19:03
@Spaak I actually added it to my Google Scholar manually. I saw they're trying to get JOSS articles indexed in PubMed automatically, but I don't know if any work is being done for Google Scholar?

**Comment by sneakers-the-rat** [comment] 2024-05-06 21:25
Confirming again that all criteria listed in google scholar's content, crawling, and indexing requirements are met: https://scholar.google.com/intl/en/scholar/inclusion.html

- with noscript enabled, can easily reach each paper in <10 clicks from homepage
- robots.txt does not exclude crawlers
- metadata on a dozen checked papers is correct according to the highwire press format (meta tags also present without JS) 

The only thing I could think of is to make a special page with all the papers from the last two weeks (the current "most recent papers" feed only lists from ~6 days ago, depending on volume), and they say:

> For websites with more than a hundred thousand papers, we recommend that you create an additional browse interface that lists only the articles added in the last two weeks. This smaller set of webpages can be recrawled more frequently than your entire browse interface, which will facilitate timely coverage of your recent papers by the search robots. 

not sure if that would help but it's the only thing they recommend that we don't do.

**Comment by arfon** [comment] 2024-10-23 18:37
> not sure if that would help but it's the only thing they recommend that we don't do.


@sneakers-the-rat we do have a table of contents now: https://joss.theoj.org/toc I wonder if that helps?

**Comment by danielskatz** [comment] 2024-10-23 18:45
I find the dates in that to quite confusing - the dd-mm-yyyy format would be clearer if it was yyyy-mm-dd. But I'm not sure where this is being generated to put in a PR...

**Comment by sneakers-the-rat** [comment] 2024-10-23 20:32
probably? it's all a black box to me.

to get to a toc page it's 

index > about > toc > issue > paper

which is less than 10 hops? so it should be fine?
