### ISSUE TITLE
Getting too many emails as reviewer

### ISSUE THREAD

**Issue by eschnett** [openjournals/joss#200] opened 2016-11-14 01:05 UTC
I am currently reviewing one paper. After the review process was set up, I started receive emails -- but not just regarding the paper/software I'm reviewing, but rather for all papers that are currently being reviewed. That's quite a few emails per day. How can I change this?

**Comment by arfon** [comment] 2016-11-14 01:19
> That's quite a few emails per day. How can I change this?

@eschnett apologies for the GitHub noise.

This is probably because you're watching the [joss-reviews repository](https://github.com/openjournals/joss-reviews). To fix this set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

In addition, you might like to change your default settings for this stuff in your GitHub profile here: https://github.com/settings/notifications 

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)

**Comment by danielskatz** [comment] 2016-11-14 02:45
I think this is more of a problem, and needs a better solution than telling the reviewers to do something extra.  Is there some way that we can get new reviewers to be not automatically subscribed to this repo?

**Comment by arfon** [comment] 2016-11-14 13:36
> Is there some way that we can get new reviewers to be not automatically subscribed to this repo?

With our current workflow, unfortunately not.

The root cause of all of this is that we allow/encourage reviewers to check off items in the first review issue (such as [this one](https://github.com/openjournals/joss-reviews/issues/116#issue-189105833)). 

In order to have permissions to 'edit' that issue (click checkboxes) the reviewer has to be a collaborator on the repository and when we programmatically give the reviewer write access on the `joss-reviews` repository they (usually) automatically watch that repository (this is the default GitHub behaviour).

The only solution I can see here is to remove the checklist but I feel like this is a useful part of the review process.

/ cc @karthik for additional insights on how rOpenSci do this.

**Comment by labarba** [comment] 2016-11-14 13:42
I think the check list is a valuable part of our review process, and reviewers need write access to the joss-reviews repo for that.

Question: usually, when I'm added to any repo, I get an auto-email from GitHub that says "you've been added ... you can unwatch here" with a link. Do reviewers get that?

**Comment by arfon** [comment] 2016-11-14 13:55
> Question: usually, when I'm added to any repo, I get an auto-email from GitHub that says "you've been added ... you can unwatch here" with a link. Do reviewers get that?

Since we do this [programmatically](https://github.com/openjournals/whedon-api/blob/master/whedon.rb#L135) I'm not sure.

One thing we could do _immediately_ is point new reviewers to [this issue](https://github.com/openjournals/joss/issues/201) describing how to reduce the notification noise but I think that's exactly what @danielskatz is saying we shouldn't need to do :-\

**Comment by kyleniemeyer** [comment] 2017-07-15 01:03
Can we close this? I'm not sure it is still a pressing issue.

**Comment by arfon** [comment] 2017-07-15 10:43
I'd vote yes.

**Closed** 2017-07-15 16:03 UTC
