### ISSUE TITLE
Pre-submission enquiry - requirement for paper.md within software repository

### ISSUE THREAD

**Issue by tonyewong** [openjournals/joss#1062] opened 2022-04-04 22:00 UTC
Hello,

I'm interested in submitting a code repository + paper to JOSS, and have a question about the following requirement.

> Your paper (paper.md and BibTeX files, plus any figures) must be hosted in a Git-based repository together with your software (although they may be in a short-lived branch which is never merged with the default).

Our submitted software will be in the form of a Julia package. The best practice for us may well be for the paper repository to use a sub-module structure associated with the model code, or to have the paper.md and associated bibtex, figures, and other auxiliary files in their own repository that properly demonstrates adding and using this separate Julia package. The short-lived branch idea above would run into a similar issue of the package trying to load/use itself.

Is there any flexibility in how the paper.md (and auxiliary files) and the main software that is being submitted to JOSS are related to one another? Or is it strictly required that they live in the same repository? 

I'm tagging @lrennels as she's also a developer on this project.

Thanks for your time and service to our community,
-Tony

**Comment by jedbrown** [comment] 2022-04-04 22:21
Hi @tonyewong, nice to see you here. It's possible to use a different repo (and some JOSS pubs are about an ecosystem that spans multiple repos) but it's encouraged and simpler if it can be in the repo. But it sounds like you want to do this for a technical reason rather than community/developer experience. Could you elaborate on
> The short-lived branch idea above would run into a similar issue of the package trying to load/use itself.

Cc: @rkurchin who often works with Julia.

**Comment by lrennels** [comment] 2022-04-04 23:30
Hi @jedbrown, one of our main motivations here is to make sure that the examples we provide to users are written in such a way that replicates what they should do on their local machine.  Because of the way Julia differentiates between Project repositories and Package repositories, especially with regards to environment instantiation, it is difficult to include the types of extended example files and notebooks we would like to add for the paper within the Package without adding unnecessary complexity.

One option we see is to include two repositories: (1) one for the package which will include all source code, a description and API instructions in a README, and testing files for continuous integration and (2) one for the paper that includes paper code as well as extended examples in notebooks and scripts. 

In our view this would be the way to be consistent with Julia protocols while transparent and friendly to users.  Another option is Github submodules, but we would like to avoid as much complexity for users as possible. That said perhaps @rkurchin has ideas about the best way to do this in Julia?

Tagging @davidanthoff as well who may have insights.

**Comment by tonyewong** [comment] 2022-04-12 19:50
Hi @jedbrown , Just wanted to circle back on this before I forget (again!). I think @lrennels  provided a thorough explanation of what we're imagining. There would be some examples of use cases within a separate paper repository that could demonstrate how a user is expected to interact with the package that the JOSS submission would be presenting.

As an example, what's currently in the [`run_downscale.jl` script here](https://github.com/raddleverse/MimiBRICK.jl/blob/master/localslr/run_downscale.jl) ought to be run out of a separate repository, that is `using MimiBRICK`. That gets a bit convoluted if the examples are within the package itself, and our sense is that providing examples in the same manner that users are expected to engage with the code would be more helpful. We're happy to defer to your editorial judgment, and thanks in advance for your and @rkurchin 's guidance!

**Comment by rkurchin** [comment] 2022-04-14 15:54
Sorry for missing the boat on this the first time around. I can see the issue you're describing. I did notice that your package doesn't currently have docs (or rather, they are entirely within the README). Having separate documentation is something that JOSS certainly encourages (though does not strictly require), and for which Julia has an ecosystem that also gets around the sorts of issues you're describing. Take a look at how [Documenter.jl](https://juliadocs.github.io/Documenter.jl/stable/) works, for instance. In my own packages, I have also made use of [PlutoStaticHTML](https://github.com/rikhuijzer/PlutoStaticHTML.jl) to write example scripts as [Pluto](https://github.com/fonsp/Pluto.jl) notebooks and then host them as part of my documentation.

As a much simpler solution if you don't want to build an entire docs site and prefer keeping things in the readme as you have now, you could just make an `examples/` folder in your repo that has Pluto notebooks, as you should be able to do `using MimiBRICK` within them (either pinning to a registered version for replicability, or by [bypassing Pluto's built-in package manager](https://github.com/fonsp/Pluto.jl/wiki/%F0%9F%8E%81-Package-management#advanced-set-up-an-environment-with-pkgactivate) and using the version in that same repo (and then directing users to a commit hash for reproducibility).

Take a look at these options and see if any of them might work for you.

**Comment by tonyewong** [comment] 2022-04-15 13:15
No worries at all! I think the notebook solution in an examples/ directory will work well enough. Our tentative plan would be to pin it to the JOSS-submission-specific version of `MimiBRICK` with `Project.` & `Manifest.toml` files in that directory.

And you're absolutely right -- the top-level `README.md` file is unwieldy! You caught us as we are refactoring things and moving some examples into docstrings, others into the `examples/` directory, and others into READMEs in the subdirectories.

If this sounds like an acceptable solution on your end, I'm happy to have the issue closed.

**Comment by jedbrown** [comment] 2022-04-15 22:22
Sounds like that gives a working strategy to have the paper in the repository (after you finish refactoring) so I'll close this. Feel free to reopen if anything further comes up. Thanks @rkurchin for the advice.

**Closed by jedbrown** 2022-04-15 22:22 UTC
