### ISSUE TITLE
JOSS pdf is not "PDF/A Compliant"

### ISSUE THREAD

**Issue by sfsinger19103** [openjournals/joss#1030] opened 2022-01-06 15:28 UTC
The US National Science Foundation, funder of the work described in my [article recently published in JOSS](https://joss.theoj.org/papers/10.21105/joss.03739), requires PDF/A compliance for publications.

> The uploaded file format is not PDF/A compliant. PDF/A is the acceptable file format for purposes of long-term preservation and archiving and to satisfy 508 Compliance requirements of the Americans with Disabilities Act (ADA). 

It would be great -- not just for compliance reasons, but for accessibility to all --  if JOSS could provide a downloadable PDF/A compliant version of each published article. How hard could it be? NSF has [some info](https://www.research.gov/common/attachment/Desktop/How_do_I_create_a_PDF-A_file.pdf).

**Comment by danielskatz** [comment] 2022-01-06 16:02
While this might be possible, I want to point out that the PDFs I get from most publishers are not PDF/A compliant, so JOSS is not alone in this failing.  Also, FYI, it's quite easy to convert PDFs into PDF/A format, at least on a Mac, as it's a simple checkbox under File->Export in Preview

**Comment by danielskatz** [comment] 2022-01-06 16:03
I wonder if our toolchain would let us create PDF/A-compliant PDFs by default? And if there would be any reason not to do this?  @arfon, any thoughts?

**Comment by jedbrown** [comment] 2022-01-06 16:05
Duplicate of #901. We need to figure out how to automate this using our workflow. It looks like it's some extra stuff we could add to the LaTeX template, but #901 had issues. This suggests PDF/A-3b is easier to generate. https://tex.stackexchange.com/a/535849

**Comment by jedbrown** [comment] 2022-01-11 23:08
We merged support in Inari so JOSS will produce PDF/A when the transition to Buffy is complete. I'll close this issue. You can watch openjournals/buffy#46 to be notified when it deploys.

**Closed by jedbrown** 2022-01-11 23:08 UTC
