### ISSUE TITLE
Add an FAQ section

### ISSUE THREAD

**Issue by daattali** [openjournals/joss#158] opened 2016-08-06 18:59 UTC
The first section in the [about](http://joss.theoj.org/about) page is kind of like an FAQ but it's called "About" instead. Would it make more sense to turn it into an FAQ?  Or perhaps add an FAQ elsewhere for more questions?

Two questions I can think of imeediately that I really wanted to find in an FAQ:
- Are _only_ short submission allowed? Why?
- What if I have a nice long vignette and want to use that instead? (point them to other journals)
- Once accepted, does my paper get indexed by Google Scholar etc?

**Comment by pjotrp** [comment] 2016-08-08 19:46
I don't think there are any constraints on the length of the submission. The source code, however, *is* the story, so we expect that to weigh in.

Google scholar does index the generated DOI. Other services, such as NCBI Pubmed, are non-automatic. That may change over time.

**Comment by arfon** [comment] 2016-08-09 00:21
@daattali thanks for posting this. I agree we could do with an FAQ section. I'll look into doing that. To answer your questions though:

> I don't think there are any constraints on the length of the submission.

There actually are. See this comment for more details: https://github.com/openjournals/joss/issues/40#issuecomment-238416918

> What if I have a nice long vignette and want to use that instead? (point them to other journals)

:+1: pretty much.

> Once accepted, does my paper get indexed by Google Scholar etc?

It _should_ yes. We're still waiting for Google to do this but we have all of the correct metadata on the paper pages since [here](https://github.com/openjournals/joss/issues/130).

> Other services, such as NCBI Pubmed, are non-automatic. That may change over time.

Yep, the best thing you can do is to cite something in JOSS, that way, other indexers are more likely to reach out to us to ask for metadata for their indexes.

**Comment by cMadan** [comment] 2016-08-09 01:19
Google Scholar has picked up my JOSS paper, though it pulled the metadata from the copy of the PDF I uploaded on my own website, rather than from the JOSS website (same PDF file though).

https://scholar.google.com/citations?view_op=view_citation&citation_for_view=2QJwoAwAAAAJ:3BvdIg-l-ZAC

**Comment by pjotrp** [comment] 2016-08-09 03:20
OK, short paper by design. Any lengthy description/explanation belongs in the docs and/or source code. 

https://github.com/openjournals/joss/issues/40#issuecomment-238416918 agree.

I think we can close this issue.

**Comment by daattali** [comment] 2016-08-09 03:45
@pjotrp the short vs long is not the issue here. I opened this issue in order to ask for an FAQ -- long vs short was just one potential FAQ :)

**Comment by pjotrp** [comment] 2016-08-09 03:46
Heh. The FAQ can point to the issue trackers ;)

**Closed** 2023-06-23 03:38 UTC
