### ISSUE TITLE
Whedon only addresses one reviewer in some messages even if multiple are assigned

### ISSUE THREAD

**Issue by mbobra** [openjournals/joss#540] opened 2019-06-05 19:27 UTC
Whedon only mentions the name of the first reviewer assigned to a paper, rather than mentioning both (or all) the reviewers, in its message that begins with:

> Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. 

It looks like the command `@whedon assign @username as reviewer` generates the message above, and the command `@whedon add @username as reviewer` does not append to Whedon's list of reviewers.

**Comment by danielskatz** [comment] 2019-06-05 19:31
Can you point to some specific problems? since I don't think this is a consistent problem

**Comment by mbobra** [comment] 2019-06-05 19:35
Yes, see openjournals/joss-reviews#1488, openjournals/joss-reviews#1469, openjournals/joss-reviews#1466, openjournals/joss-reviews#1461, and openjournals/joss-reviews#1453 (to select a few at random). It seems like a consistent problem.

**Comment by danielskatz** [comment] 2019-06-05 19:38
Ah, I see - the problem is in the second comment that whedon creates in the issue, where it just lists the first reviewer.

My guess is this is a relatively easy fix for @arfon, who I will assign this to :)

**Comment by arfon** [comment] 2019-06-05 20:13
I *think* I fixed this in https://github.com/openjournals/whedon-api/commit/c9a092f27cea2ca680b44b75ad71860c8809242c - testing...

**Closed** 2019-06-05 20:13 UTC
Labels: bug

**Comment by arfon** [comment] 2019-06-05 20:18
OK, fix is working. Thanks for spotting this @mbobra.
